[package]
name = "note-gen"
version = "0.4.5"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1", features = [] }

[dependencies]
tauri = { version = "1", features = [ "http-all", "clipboard-all", "shell-all", "dialog-open", "global-shortcut-all", "protocol-asset", "notification-all", "window-all", "path-all", "system-tray", "fs-all"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = "0.4.38"
jieba-rs = { version = "0.7", features = ["tfidf", "textrank"] }
xcap = "0.0.1"
leptess = "0.14.0"
tauri-plugin-clipboard = "1.1.4"

[features]
# This feature is used for production builds or when a dev server is not specified, DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
