import emitter from "@/lib/emitter";

const config= [
  { name: 'undo', tipPosition: 's' },
  { name: 'redo', tipPosition: 's' },
  '|',
  { name: 'headings', tipPosition: 'se',},
  { name: 'bold', tipPosition: 's' },
  { name: 'italic', tipPosition: 's' },
  { name: 'strike', tipPosition: 's' },
  { name: '|', tipPosition: 's' },
  { name: 'line', tipPosition: 's' },
  { name: 'quote', tipPosition: 's' },
  { name: 'list', tipPosition: 's' },
  { name: 'ordered-list', tipPosition: 's' },
  { name: 'check', tipPosition: 's' },
  { name: 'code', tipPosition: 's' },
  { name: 'inline-code', tipPosition: 's' },
  { name: 'upload', tipPosition: 's' },
  { name: 'link', tipPosition: 's' },
  { name: 'table', tipPosition: 's' },
  '|',
  {
    name: 'question',
    tipPosition: 's',
    tip: '问答',
    className: 'right',
    icon: '<svg><use xlink:href="#vditor-icon-question"></svg>',
    click: () => emitter.emit('toolbar-question'),
  },
  {
    name: 'continue',
    tipPosition: 's',
    tip: '续写',
    className: 'right',
    icon: '<svg><use xlink:href="#vditor-icon-list-plus"></svg>',
    click: () => emitter.emit('toolbar-continue'),
  },
  {
    name: 'translation',
    tipPosition: 's',
    tip: '翻译',
    icon: '<svg><use xlink:href="#vditor-icon-translation"></svg>',
    className: 'bottom',
  },
  '|',
  { name: 'edit-mode', tipPosition: 's', className: 'bottom' },
  { name: 'both', tipPosition: 's' },
  { name: 'preview', tipPosition: 's' },
  { name: 'outline', tipPosition: 's' },
  { name: 'export', tipPosition: 's', className: 'bottom' },
]

export default config