name: Automatic update # 该Action的名字

# on:何时触发该事件.
on:
  push:
    tags:
      - "*"

  # 允许从Actions选项卡手动运行此工作流
  workflow_dispatch:

# 工作流运行由一个或多个jobs组成，这些job可以按顺序或并行运行
jobs:
  # 此工作流包含一个名为“build-deploy”的job。
  build-deploy:
    # 改job运行于什么虚拟机上
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.19.1]

    # steps表示将作为job一部分执行的一系列任务
    steps:
      - uses: actions/checkout@v3
      - name: use pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: install and build #安装以来并打包，执行的是项目我们定义的命令
        run: |
          cd docs
          pnpm install --filter ./docs --frozen-lockfile
          pnpm run build

      - name: deploy #部署
        uses: peaceiris/actions-gh-pages@v3 #和上面一样，这里使用的是他人写好的插件库，作用是发布到其他仓库中或者其他分支上，想要具体了解可以在插件库中搜索
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/.vitepress/dist #要推送的内容（打包后的博客文件夹）
          publish_branch: gh-pages #分支名
      # - name: deploy aliyun      # 为 step 指定一个名称，将会在 github action 的控制台中显示
      #   uses: easingthemes/ssh-deploy@v5.0.3      #可以访问的仓库，实现的上传服务器步骤被封装在此action
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.TREE_HOLE }}  #这个是阿里云的私钥
      #     SOURCE: "./dist/"
      #     ARGS: "-avzr --delete --exclude '.user.ini'"
      #     REMOTE_HOST: ${{ secrets.HOST }}    #阿里云的 ip
      #     REMOTE_USER: ${{ secrets.USER }}    #阿里云用户
      #     REMOTE_PORT : "22" #远程服务器的端口
      #     TARGET: ${{ secrets.TARGET }}       #被部署的服务器路径
